export const allCities = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Pune",
    "Goa",
    "Cochin",
    "Trivandrum",
    "Lucknow",
    "Jaipur",
    "Amritsar",
    "Guwahati",
    "Nagpur",
    "Indore",
    "Vadodara",
    "Patna",
    "Coimbatore",
    "Madurai",
    "Calicut",
    "Bhubaneswar",
    "Chandigarh",
    "Ranchi",
    "Mangalore",
    "Visakhapatnam",
    "Surat",
    "Srinagar",
    "Tiruchirappalli",
    "Port Blair",
    "Varanasi",
    "Raipur",
    "Bagdogra",
    "Aurangabad",
    "Bhopal",
    "Agra",
    "Rajkot",
    "Udaipur",
    "Dubai",
    "Abu Dhabi",
    "Doha",
    "Muscat",
    "Kuwait City",
    "Colombo",
    "Male",
    "Kathmandu",
    "Dhaka",
    "Bangkok",
    "Singapore"
  ];
  